services:
  db:
    image: postgres:13
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: mora123
      POSTGRES_DB: movies_db
    ports:
      - "5432:5432"  # Expone el puerto 5432 de PostgreSQL en tu máquina local
    volumes:
      - postgres_data:/var/lib/postgresql/data  # Persiste los datos de la base de datos
      

volumes:
  postgres_data: